ALTER TABLE "Product"
ALTER COLUMN "ID"
SET NOT NULL;

ALTER TABLE "Product"
ADD CONSTRAINT "PK_Product"
PRIMARY KEY ("ID");

ALTER TABLE "Product"
ALTER COLUMN "Name"
SET NOT NULL;

ALTER TABLE "Product"
ADD CONSTRAINT "U_Product_Name"
UNIQUE ("Name");
