ALTER TABLE "Vendor"
ALTER COLUMN "ID"
SET NOT NULL;

ALTER TABLE "Vendor"
ADD CONSTRAINT "PK_Vendor"
PRIMARY KEY ("ID");

ALTER TABLE "Vendor"
ALTER COLUMN "Name"
SET NOT NULL;

ALTER TABLE "Vendor"
ADD CONSTRAINT "U_Vendor_Name"
UNIQUE ("Name");
